### ISSUE TITLE
Use gin web framework

### ISSUE THREAD

**Issue by Wen777** [Hyperpilotio/daemon-ecs-scheduler#7]

**Comment by swhsiang** [comment]
I choose to use [gin](https://github.com/gin-gonic/gin) as the web framework. It is a mature framework with an active community and big companies are using this package too. Ex: CISCO.

The document of gin states:

* Crash-free
Gin can catch a panic occurred during a HTTP request and recover it. This way, your server will be always available. It’s also possible to report this panic to Sentry for example!

**Comment by swhsiang** [comment]
Since we have the sub-command `daemon-ecs-scheduler server`, the scheduler works as a web server.
It is going to provide a RESTful API and other clients can interact with it.

Refer to #9 .
